// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: types/msg_modify_limit_swap.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	common "github.com/decaswap-labs/decanode/common"
	github_com_decaswap_labs_decanode_common "github.com/decaswap-labs/decanode/common"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgModifyLimitSwap struct {
	From                 github_com_decaswap_labs_decanode_common.Address `protobuf:"bytes,1,opt,name=from,proto3,casttype=github.com/decaswap-labs/decanode/common.Address" json:"from,omitempty"`
	Source               common.Coin                                      `protobuf:"bytes,2,opt,name=source,proto3" json:"source"`
	Target               common.Coin                                      `protobuf:"bytes,3,opt,name=target,proto3" json:"target"`
	ModifiedTargetAmount cosmossdk_io_math.Uint                           `protobuf:"bytes,4,opt,name=modified_target_amount,json=modifiedTargetAmount,proto3,customtype=cosmossdk.io/math.Uint" json:"modified_target_amount"`
	Signer               github_com_cosmos_cosmos_sdk_types.AccAddress    `protobuf:"bytes,5,opt,name=signer,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"signer,omitempty"`
	DepositAsset         common.Asset                                     `protobuf:"bytes,6,opt,name=deposit_asset,json=depositAsset,proto3" json:"deposit_asset"`
	DepositAmount        cosmossdk_io_math.Uint                           `protobuf:"bytes,7,opt,name=deposit_amount,json=depositAmount,proto3,customtype=cosmossdk.io/math.Uint" json:"deposit_amount"`
}

func (m *MsgModifyLimitSwap) Reset()         { *m = MsgModifyLimitSwap{} }
func (m *MsgModifyLimitSwap) String() string { return proto.CompactTextString(m) }
func (*MsgModifyLimitSwap) ProtoMessage()    {}
func (*MsgModifyLimitSwap) Descriptor() ([]byte, []int) {
	return fileDescriptor_083238984b03d665, []int{0}
}
func (m *MsgModifyLimitSwap) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgModifyLimitSwap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgModifyLimitSwap.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgModifyLimitSwap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgModifyLimitSwap.Merge(m, src)
}
func (m *MsgModifyLimitSwap) XXX_Size() int {
	return m.Size()
}
func (m *MsgModifyLimitSwap) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgModifyLimitSwap.DiscardUnknown(m)
}

var xxx_messageInfo_MsgModifyLimitSwap proto.InternalMessageInfo

func (m *MsgModifyLimitSwap) GetFrom() github_com_decaswap_labs_decanode_common.Address {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *MsgModifyLimitSwap) GetSource() common.Coin {
	if m != nil {
		return m.Source
	}
	return common.Coin{}
}

func (m *MsgModifyLimitSwap) GetTarget() common.Coin {
	if m != nil {
		return m.Target
	}
	return common.Coin{}
}

func (m *MsgModifyLimitSwap) GetSigner() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.Signer
	}
	return nil
}

func (m *MsgModifyLimitSwap) GetDepositAsset() common.Asset {
	if m != nil {
		return m.DepositAsset
	}
	return common.Asset{}
}

func init() {
	proto.RegisterType((*MsgModifyLimitSwap)(nil), "types.MsgModifyLimitSwap")
}

func init() { proto.RegisterFile("types/msg_modify_limit_swap.proto", fileDescriptor_083238984b03d665) }

var fileDescriptor_083238984b03d665 = []byte{
	// 462 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x31, 0x6f, 0xd3, 0x40,
	0x14, 0x8e, 0x21, 0x35, 0xc2, 0xa4, 0x48, 0x98, 0xaa, 0x58, 0x15, 0x72, 0x02, 0x53, 0x14, 0x11,
	0x1f, 0x34, 0x0c, 0x08, 0xb1, 0x24, 0x08, 0x89, 0x81, 0x2c, 0x21, 0x2c, 0x2c, 0xd6, 0xe5, 0xee,
	0x6a, 0x9f, 0xda, 0xf3, 0xb3, 0x7c, 0x17, 0x4a, 0x57, 0x46, 0x26, 0x58, 0xf9, 0x15, 0xfd, 0x19,
	0x1d, 0x3b, 0x22, 0x86, 0x08, 0x25, 0x43, 0xff, 0x43, 0x27, 0xe4, 0x77, 0x67, 0x40, 0x42, 0x08,
	0x16, 0xbf, 0xf3, 0x77, 0xdf, 0x7b, 0xef, 0xfb, 0xde, 0xbd, 0xe0, 0x9e, 0x39, 0x29, 0x85, 0x26,
	0x4a, 0x67, 0xa9, 0x02, 0x2e, 0x0f, 0x4e, 0xd2, 0x23, 0xa9, 0xa4, 0x49, 0xf5, 0x31, 0x2d, 0x93,
	0xb2, 0x02, 0x03, 0xe1, 0x16, 0x52, 0xf6, 0x6e, 0x33, 0x50, 0x0a, 0x0a, 0x62, 0x83, 0xbd, 0xdb,
	0xdb, 0xc9, 0x20, 0x03, 0x3c, 0x92, 0xfa, 0xe4, 0xd0, 0x5b, 0x54, 0xc9, 0x02, 0x08, 0x7e, 0x1d,
	0x74, 0x87, 0x81, 0x56, 0x80, 0x8d, 0xc8, 0xbb, 0x47, 0x75, 0xb0, 0x17, 0xf7, 0x3f, 0xb7, 0x83,
	0x70, 0xaa, 0xb3, 0x29, 0x36, 0x7f, 0x55, 0xf7, 0x7e, 0x7d, 0x4c, 0xcb, 0xf0, 0x65, 0xd0, 0x3e,
	0xa8, 0x40, 0x45, 0x5e, 0xcf, 0xeb, 0x5f, 0x9f, 0x3c, 0xbe, 0x5c, 0x75, 0x1f, 0x66, 0xd2, 0xe4,
	0xcb, 0x45, 0xc2, 0x40, 0x11, 0x2e, 0x18, 0xad, 0x15, 0x0e, 0x8f, 0xe8, 0x42, 0xe3, 0x5f, 0x01,
	0x5c, 0x34, 0xd2, 0xc6, 0x9c, 0x57, 0x42, 0xeb, 0x19, 0x56, 0x08, 0x07, 0x81, 0xaf, 0x61, 0x59,
	0x31, 0x11, 0x5d, 0xe9, 0x79, 0xfd, 0x1b, 0xfb, 0x9d, 0xc4, 0xd1, 0x9e, 0x83, 0x2c, 0x26, 0xed,
	0xb3, 0x55, 0xb7, 0x35, 0x73, 0x8c, 0x9a, 0x6b, 0x68, 0x95, 0x09, 0x13, 0x5d, 0xfd, 0x3b, 0xd7,
	0x32, 0xc2, 0x79, 0xb0, 0x8b, 0x13, 0x93, 0x82, 0xa7, 0x16, 0x4a, 0xa9, 0x82, 0x65, 0x61, 0xa2,
	0x36, 0x6a, 0x8e, 0x6b, 0xf6, 0xb7, 0x55, 0x77, 0xd7, 0x3a, 0xd7, 0xfc, 0x30, 0x91, 0x40, 0x14,
	0x35, 0x79, 0xf2, 0x46, 0x16, 0x66, 0xb6, 0xd3, 0x64, 0xcf, 0x31, 0x79, 0x8c, 0xb9, 0xe1, 0x3c,
	0xf0, 0xb5, 0xcc, 0x0a, 0x51, 0x45, 0x5b, 0x3d, 0xaf, 0xdf, 0x99, 0x3c, 0xbb, 0x5c, 0x75, 0x87,
	0xbf, 0x39, 0x77, 0x63, 0xb4, 0x61, 0xa8, 0xf9, 0x21, 0xc1, 0xd7, 0x49, 0xc6, 0x8c, 0x39, 0xdb,
	0x5f, 0x2e, 0x4e, 0x07, 0xfe, 0x42, 0xb0, 0x7c, 0xb4, 0x3f, 0x73, 0xb5, 0xc2, 0x27, 0xc1, 0x36,
	0x17, 0x25, 0x68, 0x69, 0x52, 0xaa, 0xb5, 0x30, 0x91, 0x8f, 0xf6, 0xb6, 0x1b, 0x7b, 0xe3, 0x1a,
	0x74, 0xfe, 0x3a, 0x8e, 0x89, 0x58, 0xf8, 0x22, 0xb8, 0xf9, 0x33, 0xd3, 0xba, 0xbb, 0xf6, 0x5f,
	0xee, 0x9a, 0x7e, 0xd6, 0xd6, 0xd3, 0x07, 0x1f, 0x6a, 0x55, 0x56, 0xcd, 0xc7, 0x8b, 0xd3, 0xc1,
	0x5d, 0x93, 0x43, 0xc5, 0x72, 0x2a, 0x0b, 0xf2, 0xe7, 0xe3, 0x4f, 0xa6, 0x67, 0xeb, 0xd8, 0x3b,
	0x5f, 0xc7, 0xde, 0xf7, 0x75, 0xec, 0x7d, 0xda, 0xc4, 0xad, 0xf3, 0x4d, 0xdc, 0xfa, 0xba, 0x89,
	0x5b, 0x6f, 0x47, 0xff, 0x5e, 0x82, 0xf7, 0xe4, 0x57, 0x6d, 0x9c, 0xcd, 0xc2, 0xc7, 0x4d, 0x1b,
	0xfd, 0x08, 0x00, 0x00, 0xff, 0xff, 0x8b, 0xdd, 0x24, 0x35, 0xec, 0x02, 0x00, 0x00,
}

func (m *MsgModifyLimitSwap) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgModifyLimitSwap) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgModifyLimitSwap) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.DepositAmount.Size()
		i -= size
		if _, err := m.DepositAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMsgModifyLimitSwap(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	{
		size, err := m.DepositAsset.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintMsgModifyLimitSwap(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintMsgModifyLimitSwap(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0x2a
	}
	{
		size := m.ModifiedTargetAmount.Size()
		i -= size
		if _, err := m.ModifiedTargetAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMsgModifyLimitSwap(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size, err := m.Target.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintMsgModifyLimitSwap(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.Source.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintMsgModifyLimitSwap(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.From) > 0 {
		i -= len(m.From)
		copy(dAtA[i:], m.From)
		i = encodeVarintMsgModifyLimitSwap(dAtA, i, uint64(len(m.From)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintMsgModifyLimitSwap(dAtA []byte, offset int, v uint64) int {
	offset -= sovMsgModifyLimitSwap(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgModifyLimitSwap) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.From)
	if l > 0 {
		n += 1 + l + sovMsgModifyLimitSwap(uint64(l))
	}
	l = m.Source.Size()
	n += 1 + l + sovMsgModifyLimitSwap(uint64(l))
	l = m.Target.Size()
	n += 1 + l + sovMsgModifyLimitSwap(uint64(l))
	l = m.ModifiedTargetAmount.Size()
	n += 1 + l + sovMsgModifyLimitSwap(uint64(l))
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovMsgModifyLimitSwap(uint64(l))
	}
	l = m.DepositAsset.Size()
	n += 1 + l + sovMsgModifyLimitSwap(uint64(l))
	l = m.DepositAmount.Size()
	n += 1 + l + sovMsgModifyLimitSwap(uint64(l))
	return n
}

func sovMsgModifyLimitSwap(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMsgModifyLimitSwap(x uint64) (n int) {
	return sovMsgModifyLimitSwap(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgModifyLimitSwap) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgModifyLimitSwap
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgModifyLimitSwap: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgModifyLimitSwap: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field From", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgModifyLimitSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgModifyLimitSwap
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgModifyLimitSwap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.From = github_com_decaswap_labs_decanode_common.Address(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Source", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgModifyLimitSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgModifyLimitSwap
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgModifyLimitSwap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Source.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Target", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgModifyLimitSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgModifyLimitSwap
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgModifyLimitSwap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Target.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModifiedTargetAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgModifyLimitSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgModifyLimitSwap
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgModifyLimitSwap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ModifiedTargetAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgModifyLimitSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMsgModifyLimitSwap
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgModifyLimitSwap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = append(m.Signer[:0], dAtA[iNdEx:postIndex]...)
			if m.Signer == nil {
				m.Signer = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepositAsset", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgModifyLimitSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgModifyLimitSwap
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgModifyLimitSwap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DepositAsset.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepositAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgModifyLimitSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgModifyLimitSwap
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgModifyLimitSwap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DepositAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsgModifyLimitSwap(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMsgModifyLimitSwap
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMsgModifyLimitSwap(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMsgModifyLimitSwap
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgModifyLimitSwap
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgModifyLimitSwap
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMsgModifyLimitSwap
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMsgModifyLimitSwap
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMsgModifyLimitSwap
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMsgModifyLimitSwap        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMsgModifyLimitSwap          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMsgModifyLimitSwap = fmt.Errorf("proto: unexpected end of group")
)
