// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: types/msg_operator_rotate.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	common "github.com/decaswap-labs/decanode/common"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgOperatorRotate struct {
	Signer          github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,1,opt,name=signer,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"signer,omitempty"`
	OperatorAddress github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,2,opt,name=operator_address,json=operatorAddress,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"operator_address,omitempty"`
	Coin            common.Coin                                   `protobuf:"bytes,3,opt,name=coin,proto3" json:"coin"`
}

func (m *MsgOperatorRotate) Reset()         { *m = MsgOperatorRotate{} }
func (m *MsgOperatorRotate) String() string { return proto.CompactTextString(m) }
func (*MsgOperatorRotate) ProtoMessage()    {}
func (*MsgOperatorRotate) Descriptor() ([]byte, []int) {
	return fileDescriptor_9aab50b9a3a57093, []int{0}
}
func (m *MsgOperatorRotate) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgOperatorRotate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgOperatorRotate.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgOperatorRotate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgOperatorRotate.Merge(m, src)
}
func (m *MsgOperatorRotate) XXX_Size() int {
	return m.Size()
}
func (m *MsgOperatorRotate) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgOperatorRotate.DiscardUnknown(m)
}

var xxx_messageInfo_MsgOperatorRotate proto.InternalMessageInfo

func (m *MsgOperatorRotate) GetSigner() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.Signer
	}
	return nil
}

func (m *MsgOperatorRotate) GetOperatorAddress() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.OperatorAddress
	}
	return nil
}

func (m *MsgOperatorRotate) GetCoin() common.Coin {
	if m != nil {
		return m.Coin
	}
	return common.Coin{}
}

func init() {
	proto.RegisterType((*MsgOperatorRotate)(nil), "types.MsgOperatorRotate")
}

func init() { proto.RegisterFile("types/msg_operator_rotate.proto", fileDescriptor_9aab50b9a3a57093) }

var fileDescriptor_9aab50b9a3a57093 = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x90, 0xb1, 0x4e, 0xf3, 0x30,
	0x14, 0x85, 0xe3, 0xff, 0x2f, 0x1d, 0x42, 0x25, 0x20, 0x30, 0x44, 0x1d, 0x9c, 0x8a, 0x01, 0x75,
	0x49, 0x2c, 0xe8, 0x13, 0x34, 0x4c, 0x0c, 0x15, 0x52, 0x46, 0x84, 0x54, 0x39, 0x8e, 0xe5, 0x44,
	0x10, 0xdf, 0xc8, 0xd7, 0x08, 0x78, 0x0b, 0x1e, 0xab, 0x63, 0x47, 0xa6, 0x0a, 0x25, 0x3c, 0x05,
	0x13, 0xc2, 0x09, 0x88, 0x99, 0xe9, 0x1e, 0x9f, 0x63, 0x7d, 0x3e, 0xbe, 0x7e, 0x64, 0x9f, 0x1b,
	0x89, 0xac, 0x46, 0xb5, 0x86, 0x46, 0x1a, 0x6e, 0xc1, 0xac, 0x0d, 0x58, 0x6e, 0x65, 0xd2, 0x18,
	0xb0, 0x10, 0xec, 0xb9, 0x0b, 0xd3, 0x63, 0x01, 0x75, 0x0d, 0x9a, 0xf5, 0xa3, 0xcf, 0xa6, 0x27,
	0x0a, 0x14, 0x38, 0xc9, 0xbe, 0x54, 0xef, 0x9e, 0xbe, 0x13, 0xff, 0x68, 0x85, 0xea, 0x7a, 0xc0,
	0x65, 0x8e, 0x16, 0x5c, 0xf9, 0x63, 0xac, 0x94, 0x96, 0x26, 0x24, 0x33, 0x32, 0x9f, 0xa4, 0xe7,
	0x1f, 0xbb, 0x28, 0x56, 0x95, 0x2d, 0x1f, 0xf2, 0x44, 0x40, 0xcd, 0x04, 0x60, 0x0d, 0x38, 0x8c,
	0x18, 0x8b, 0x3b, 0xe6, 0x1e, 0x4e, 0x96, 0x42, 0x2c, 0x8b, 0xc2, 0x48, 0xc4, 0x6c, 0x00, 0x04,
	0xb7, 0xfe, 0xe1, 0x4f, 0x57, 0xde, 0x67, 0xe1, 0xbf, 0xbf, 0x42, 0x0f, 0xbe, 0x51, 0x83, 0x11,
	0x9c, 0xf9, 0x23, 0x01, 0x95, 0x0e, 0xff, 0xcf, 0xc8, 0x7c, 0xff, 0x62, 0x92, 0x0c, 0x3f, 0xbe,
	0x84, 0x4a, 0xa7, 0xa3, 0xcd, 0x2e, 0xf2, 0x32, 0x97, 0xa7, 0xab, 0x4d, 0x4b, 0xc9, 0xb6, 0xa5,
	0xe4, 0xad, 0xa5, 0xe4, 0xa5, 0xa3, 0xde, 0xb6, 0xa3, 0xde, 0x6b, 0x47, 0xbd, 0x9b, 0xc5, 0xaf,
	0x06, 0x85, 0x14, 0x1c, 0x1f, 0x79, 0x13, 0xdf, 0xf3, 0x1c, 0xdd, 0x49, 0x43, 0x21, 0xd9, 0x13,
	0xb3, 0x25, 0x18, 0x51, 0xf2, 0x4a, 0xf7, 0x95, 0xf2, 0xb1, 0x5b, 0xde, 0xe2, 0x33, 0x00, 0x00,
	0xff, 0xff, 0xad, 0xe1, 0x4e, 0xd0, 0x91, 0x01, 0x00, 0x00,
}

func (m *MsgOperatorRotate) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgOperatorRotate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgOperatorRotate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Coin.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintMsgOperatorRotate(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.OperatorAddress) > 0 {
		i -= len(m.OperatorAddress)
		copy(dAtA[i:], m.OperatorAddress)
		i = encodeVarintMsgOperatorRotate(dAtA, i, uint64(len(m.OperatorAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintMsgOperatorRotate(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintMsgOperatorRotate(dAtA []byte, offset int, v uint64) int {
	offset -= sovMsgOperatorRotate(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgOperatorRotate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovMsgOperatorRotate(uint64(l))
	}
	l = len(m.OperatorAddress)
	if l > 0 {
		n += 1 + l + sovMsgOperatorRotate(uint64(l))
	}
	l = m.Coin.Size()
	n += 1 + l + sovMsgOperatorRotate(uint64(l))
	return n
}

func sovMsgOperatorRotate(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMsgOperatorRotate(x uint64) (n int) {
	return sovMsgOperatorRotate(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgOperatorRotate) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgOperatorRotate
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgOperatorRotate: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgOperatorRotate: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgOperatorRotate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMsgOperatorRotate
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgOperatorRotate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = append(m.Signer[:0], dAtA[iNdEx:postIndex]...)
			if m.Signer == nil {
				m.Signer = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OperatorAddress", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgOperatorRotate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMsgOperatorRotate
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgOperatorRotate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OperatorAddress = append(m.OperatorAddress[:0], dAtA[iNdEx:postIndex]...)
			if m.OperatorAddress == nil {
				m.OperatorAddress = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Coin", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgOperatorRotate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgOperatorRotate
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgOperatorRotate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Coin.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsgOperatorRotate(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMsgOperatorRotate
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMsgOperatorRotate(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMsgOperatorRotate
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgOperatorRotate
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgOperatorRotate
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMsgOperatorRotate
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMsgOperatorRotate
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMsgOperatorRotate
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMsgOperatorRotate        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMsgOperatorRotate          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMsgOperatorRotate = fmt.Errorf("proto: unexpected end of group")
)
