// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: types/query_limit_swaps.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryLimitSwapsRequest struct {
	Height      string `protobuf:"bytes,1,opt,name=height,proto3" json:"height,omitempty"`
	Offset      uint64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit       uint64 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	SourceAsset string `protobuf:"bytes,4,opt,name=source_asset,json=sourceAsset,proto3" json:"source_asset,omitempty"`
	TargetAsset string `protobuf:"bytes,5,opt,name=target_asset,json=targetAsset,proto3" json:"target_asset,omitempty"`
	Sender      string `protobuf:"bytes,6,opt,name=sender,proto3" json:"sender,omitempty"`
	SortBy      string `protobuf:"bytes,7,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	SortOrder   string `protobuf:"bytes,8,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
}

func (m *QueryLimitSwapsRequest) Reset()         { *m = QueryLimitSwapsRequest{} }
func (m *QueryLimitSwapsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryLimitSwapsRequest) ProtoMessage()    {}
func (*QueryLimitSwapsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d6fb9bbae8da701, []int{0}
}
func (m *QueryLimitSwapsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLimitSwapsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLimitSwapsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLimitSwapsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLimitSwapsRequest.Merge(m, src)
}
func (m *QueryLimitSwapsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryLimitSwapsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLimitSwapsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLimitSwapsRequest proto.InternalMessageInfo

func (m *QueryLimitSwapsRequest) GetHeight() string {
	if m != nil {
		return m.Height
	}
	return ""
}

func (m *QueryLimitSwapsRequest) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *QueryLimitSwapsRequest) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *QueryLimitSwapsRequest) GetSourceAsset() string {
	if m != nil {
		return m.SourceAsset
	}
	return ""
}

func (m *QueryLimitSwapsRequest) GetTargetAsset() string {
	if m != nil {
		return m.TargetAsset
	}
	return ""
}

func (m *QueryLimitSwapsRequest) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *QueryLimitSwapsRequest) GetSortBy() string {
	if m != nil {
		return m.SortBy
	}
	return ""
}

func (m *QueryLimitSwapsRequest) GetSortOrder() string {
	if m != nil {
		return m.SortOrder
	}
	return ""
}

type LimitSwapWithDetails struct {
	Swap               *MsgSwap `protobuf:"bytes,1,opt,name=swap,proto3" json:"swap,omitempty"`
	Ratio              string   `protobuf:"bytes,2,opt,name=ratio,proto3" json:"ratio,omitempty"`
	BlocksSinceCreated int64    `protobuf:"varint,3,opt,name=blocks_since_created,json=blocksSinceCreated,proto3" json:"blocks_since_created,omitempty"`
	TimeToExpiryBlocks int64    `protobuf:"varint,4,opt,name=time_to_expiry_blocks,json=timeToExpiryBlocks,proto3" json:"time_to_expiry_blocks,omitempty"`
	CreatedTimestamp   int64    `protobuf:"varint,5,opt,name=created_timestamp,json=createdTimestamp,proto3" json:"created_timestamp,omitempty"`
}

func (m *LimitSwapWithDetails) Reset()         { *m = LimitSwapWithDetails{} }
func (m *LimitSwapWithDetails) String() string { return proto.CompactTextString(m) }
func (*LimitSwapWithDetails) ProtoMessage()    {}
func (*LimitSwapWithDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d6fb9bbae8da701, []int{1}
}
func (m *LimitSwapWithDetails) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LimitSwapWithDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LimitSwapWithDetails.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LimitSwapWithDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LimitSwapWithDetails.Merge(m, src)
}
func (m *LimitSwapWithDetails) XXX_Size() int {
	return m.Size()
}
func (m *LimitSwapWithDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_LimitSwapWithDetails.DiscardUnknown(m)
}

var xxx_messageInfo_LimitSwapWithDetails proto.InternalMessageInfo

func (m *LimitSwapWithDetails) GetSwap() *MsgSwap {
	if m != nil {
		return m.Swap
	}
	return nil
}

func (m *LimitSwapWithDetails) GetRatio() string {
	if m != nil {
		return m.Ratio
	}
	return ""
}

func (m *LimitSwapWithDetails) GetBlocksSinceCreated() int64 {
	if m != nil {
		return m.BlocksSinceCreated
	}
	return 0
}

func (m *LimitSwapWithDetails) GetTimeToExpiryBlocks() int64 {
	if m != nil {
		return m.TimeToExpiryBlocks
	}
	return 0
}

func (m *LimitSwapWithDetails) GetCreatedTimestamp() int64 {
	if m != nil {
		return m.CreatedTimestamp
	}
	return 0
}

type PaginationMeta struct {
	Offset  uint64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit   uint64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Total   uint64 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	HasNext bool   `protobuf:"varint,4,opt,name=has_next,json=hasNext,proto3" json:"has_next,omitempty"`
	HasPrev bool   `protobuf:"varint,5,opt,name=has_prev,json=hasPrev,proto3" json:"has_prev,omitempty"`
}

func (m *PaginationMeta) Reset()         { *m = PaginationMeta{} }
func (m *PaginationMeta) String() string { return proto.CompactTextString(m) }
func (*PaginationMeta) ProtoMessage()    {}
func (*PaginationMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d6fb9bbae8da701, []int{2}
}
func (m *PaginationMeta) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PaginationMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PaginationMeta.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PaginationMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaginationMeta.Merge(m, src)
}
func (m *PaginationMeta) XXX_Size() int {
	return m.Size()
}
func (m *PaginationMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_PaginationMeta.DiscardUnknown(m)
}

var xxx_messageInfo_PaginationMeta proto.InternalMessageInfo

func (m *PaginationMeta) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *PaginationMeta) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *PaginationMeta) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *PaginationMeta) GetHasNext() bool {
	if m != nil {
		return m.HasNext
	}
	return false
}

func (m *PaginationMeta) GetHasPrev() bool {
	if m != nil {
		return m.HasPrev
	}
	return false
}

type QueryLimitSwapsResponse struct {
	LimitSwaps []*LimitSwapWithDetails `protobuf:"bytes,1,rep,name=limit_swaps,json=limitSwaps,proto3" json:"limit_swaps,omitempty"`
	Pagination *PaginationMeta         `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryLimitSwapsResponse) Reset()         { *m = QueryLimitSwapsResponse{} }
func (m *QueryLimitSwapsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryLimitSwapsResponse) ProtoMessage()    {}
func (*QueryLimitSwapsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d6fb9bbae8da701, []int{3}
}
func (m *QueryLimitSwapsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLimitSwapsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLimitSwapsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLimitSwapsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLimitSwapsResponse.Merge(m, src)
}
func (m *QueryLimitSwapsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryLimitSwapsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLimitSwapsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLimitSwapsResponse proto.InternalMessageInfo

func (m *QueryLimitSwapsResponse) GetLimitSwaps() []*LimitSwapWithDetails {
	if m != nil {
		return m.LimitSwaps
	}
	return nil
}

func (m *QueryLimitSwapsResponse) GetPagination() *PaginationMeta {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryLimitSwapsRequest)(nil), "types.QueryLimitSwapsRequest")
	proto.RegisterType((*LimitSwapWithDetails)(nil), "types.LimitSwapWithDetails")
	proto.RegisterType((*PaginationMeta)(nil), "types.PaginationMeta")
	proto.RegisterType((*QueryLimitSwapsResponse)(nil), "types.QueryLimitSwapsResponse")
}

func init() { proto.RegisterFile("types/query_limit_swaps.proto", fileDescriptor_6d6fb9bbae8da701) }

var fileDescriptor_6d6fb9bbae8da701 = []byte{
	// 552 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x93, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0xbb, 0x4d, 0x93, 0x36, 0x1b, 0x54, 0xc1, 0xca, 0x4d, 0x4d, 0x51, 0xad, 0x90, 0x53,
	0x24, 0x44, 0x0c, 0xa9, 0xb8, 0x71, 0x21, 0xc0, 0x8d, 0x40, 0x71, 0x2b, 0x21, 0x71, 0xb1, 0x36,
	0xce, 0xd4, 0x5e, 0xe1, 0x78, 0xdd, 0xdd, 0x4d, 0x49, 0x5e, 0x81, 0x03, 0xe2, 0xb1, 0x38, 0xf6,
	0xc8, 0x11, 0x25, 0xaf, 0xc0, 0x03, 0xa0, 0x9d, 0x75, 0xa2, 0x20, 0x7a, 0xcb, 0xfc, 0xdf, 0xcc,
	0x64, 0xfe, 0x99, 0x35, 0x3d, 0x35, 0x8b, 0x12, 0x74, 0x78, 0x3d, 0x03, 0xb5, 0x88, 0x73, 0x31,
	0x15, 0x26, 0xd6, 0x5f, 0x79, 0xa9, 0xfb, 0xa5, 0x92, 0x46, 0xb2, 0x3a, 0xe2, 0x13, 0x2f, 0x95,
	0xa9, 0x44, 0x25, 0xb4, 0xbf, 0x1c, 0x3c, 0xf1, 0x5c, 0xed, 0x54, 0xa7, 0x58, 0xe3, 0xd4, 0xee,
	0x1f, 0x42, 0xdb, 0x1f, 0x6d, 0xbb, 0x77, 0xb6, 0xdb, 0x85, 0x6d, 0x16, 0xc1, 0xf5, 0x0c, 0xb4,
	0x61, 0x6d, 0xda, 0xc8, 0x40, 0xa4, 0x99, 0xf1, 0x49, 0x87, 0xf4, 0x9a, 0x51, 0x15, 0x59, 0x5d,
	0x5e, 0x5d, 0x69, 0x30, 0xfe, 0x6e, 0x87, 0xf4, 0xf6, 0xa2, 0x2a, 0x62, 0x1e, 0xad, 0xe3, 0x48,
	0x7e, 0x0d, 0x65, 0x17, 0xb0, 0xc7, 0xf4, 0x9e, 0x96, 0x33, 0x95, 0x40, 0xcc, 0xb5, 0xad, 0xd9,
	0xc3, 0x5e, 0x2d, 0xa7, 0xbd, 0xb2, 0x92, 0x4d, 0x31, 0x5c, 0xa5, 0x60, 0xaa, 0x94, 0xba, 0x4b,
	0x71, 0x9a, 0x4b, 0x69, 0xd3, 0x86, 0x86, 0x62, 0x02, 0xca, 0x6f, 0xb8, 0x59, 0x5c, 0xc4, 0x8e,
	0xe9, 0xbe, 0x96, 0xca, 0xc4, 0xe3, 0x85, 0xbf, 0x5f, 0x01, 0xa9, 0xcc, 0x70, 0xc1, 0x4e, 0x29,
	0x45, 0x20, 0x95, 0x2d, 0x3a, 0x40, 0xd6, 0xb4, 0xca, 0x07, 0x2b, 0x74, 0x97, 0x84, 0x7a, 0x1b,
	0xc7, 0x9f, 0x84, 0xc9, 0xde, 0x80, 0xe1, 0x22, 0xd7, 0xac, 0x4b, 0xf7, 0xec, 0x76, 0xd0, 0x72,
	0x6b, 0x70, 0xd8, 0xc7, 0xa5, 0xf5, 0x47, 0x3a, 0xb5, 0x89, 0x11, 0x32, 0x6b, 0x54, 0x71, 0x23,
	0x24, 0xfa, 0x6f, 0x46, 0x2e, 0x60, 0xcf, 0xa8, 0x37, 0xce, 0x65, 0xf2, 0x45, 0xc7, 0x5a, 0x14,
	0x09, 0xc4, 0x89, 0x02, 0x6e, 0x60, 0x82, 0xdb, 0xa8, 0x45, 0xcc, 0xb1, 0x0b, 0x8b, 0x5e, 0x3b,
	0xc2, 0x9e, 0xd3, 0x23, 0x23, 0xa6, 0x10, 0x1b, 0x19, 0xc3, 0xbc, 0x14, 0x6a, 0x11, 0xbb, 0x24,
	0xdc, 0x51, 0x2d, 0x62, 0x16, 0x5e, 0xca, 0xb7, 0x88, 0x86, 0x48, 0xd8, 0x13, 0xfa, 0xa0, 0xea,
	0x1b, 0x5b, 0xaa, 0x0d, 0x9f, 0x96, 0xb8, 0xaf, 0x5a, 0x74, 0xbf, 0x02, 0x97, 0x6b, 0xbd, 0xfb,
	0x8d, 0xd0, 0xc3, 0x73, 0x9e, 0x8a, 0xc2, 0xce, 0x57, 0x8c, 0xc0, 0xf0, 0xad, 0xdb, 0x91, 0xbb,
	0x6f, 0xb7, 0xbb, 0x7d, 0x3b, 0x8f, 0xd6, 0x8d, 0x34, 0x3c, 0x5f, 0x5f, 0x14, 0x03, 0xf6, 0x90,
	0x1e, 0x64, 0x5c, 0xc7, 0x05, 0xcc, 0xdd, 0x35, 0x0f, 0xa2, 0xfd, 0x8c, 0xeb, 0xf7, 0x30, 0x37,
	0x6b, 0x54, 0x2a, 0xb8, 0xc1, 0xa9, 0x1c, 0x3a, 0x57, 0x70, 0xd3, 0xfd, 0x4e, 0xe8, 0xf1, 0x7f,
	0x0f, 0x4d, 0x97, 0xb2, 0xd0, 0xc0, 0x5e, 0xd2, 0xd6, 0xd6, 0x63, 0xf6, 0x49, 0xa7, 0xd6, 0x6b,
	0x0d, 0x1e, 0x55, 0xbb, 0xbf, 0xeb, 0x4c, 0x11, 0xcd, 0x37, 0x5d, 0xd8, 0x0b, 0x4a, 0xcb, 0x8d,
	0x4b, 0x34, 0xd0, 0x1a, 0x1c, 0x55, 0xc5, 0xff, 0xda, 0x8f, 0xb6, 0x12, 0x87, 0xa3, 0x9f, 0xcb,
	0x80, 0xdc, 0x2e, 0x03, 0xf2, 0x7b, 0x19, 0x90, 0x1f, 0xab, 0x60, 0xe7, 0x76, 0x15, 0xec, 0xfc,
	0x5a, 0x05, 0x3b, 0x9f, 0xcf, 0x52, 0x61, 0xb2, 0xd9, 0xb8, 0x9f, 0xc8, 0x69, 0x38, 0x81, 0x84,
	0xdb, 0xa9, 0x9e, 0xe6, 0x7c, 0xac, 0x31, 0x2a, 0xe4, 0x04, 0xc2, 0x79, 0x68, 0x32, 0xa9, 0x92,
	0x8c, 0x8b, 0x22, 0xc4, 0x7f, 0x1a, 0x37, 0xf0, 0x7b, 0x3a, 0xfb, 0x1b, 0x00, 0x00, 0xff, 0xff,
	0xe9, 0xd0, 0xd5, 0x64, 0xa3, 0x03, 0x00, 0x00,
}

func (m *QueryLimitSwapsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLimitSwapsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLimitSwapsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SortOrder) > 0 {
		i -= len(m.SortOrder)
		copy(dAtA[i:], m.SortOrder)
		i = encodeVarintQueryLimitSwaps(dAtA, i, uint64(len(m.SortOrder)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.SortBy) > 0 {
		i -= len(m.SortBy)
		copy(dAtA[i:], m.SortBy)
		i = encodeVarintQueryLimitSwaps(dAtA, i, uint64(len(m.SortBy)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintQueryLimitSwaps(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.TargetAsset) > 0 {
		i -= len(m.TargetAsset)
		copy(dAtA[i:], m.TargetAsset)
		i = encodeVarintQueryLimitSwaps(dAtA, i, uint64(len(m.TargetAsset)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.SourceAsset) > 0 {
		i -= len(m.SourceAsset)
		copy(dAtA[i:], m.SourceAsset)
		i = encodeVarintQueryLimitSwaps(dAtA, i, uint64(len(m.SourceAsset)))
		i--
		dAtA[i] = 0x22
	}
	if m.Limit != 0 {
		i = encodeVarintQueryLimitSwaps(dAtA, i, uint64(m.Limit))
		i--
		dAtA[i] = 0x18
	}
	if m.Offset != 0 {
		i = encodeVarintQueryLimitSwaps(dAtA, i, uint64(m.Offset))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Height) > 0 {
		i -= len(m.Height)
		copy(dAtA[i:], m.Height)
		i = encodeVarintQueryLimitSwaps(dAtA, i, uint64(len(m.Height)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *LimitSwapWithDetails) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LimitSwapWithDetails) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LimitSwapWithDetails) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CreatedTimestamp != 0 {
		i = encodeVarintQueryLimitSwaps(dAtA, i, uint64(m.CreatedTimestamp))
		i--
		dAtA[i] = 0x28
	}
	if m.TimeToExpiryBlocks != 0 {
		i = encodeVarintQueryLimitSwaps(dAtA, i, uint64(m.TimeToExpiryBlocks))
		i--
		dAtA[i] = 0x20
	}
	if m.BlocksSinceCreated != 0 {
		i = encodeVarintQueryLimitSwaps(dAtA, i, uint64(m.BlocksSinceCreated))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Ratio) > 0 {
		i -= len(m.Ratio)
		copy(dAtA[i:], m.Ratio)
		i = encodeVarintQueryLimitSwaps(dAtA, i, uint64(len(m.Ratio)))
		i--
		dAtA[i] = 0x12
	}
	if m.Swap != nil {
		{
			size, err := m.Swap.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQueryLimitSwaps(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PaginationMeta) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PaginationMeta) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PaginationMeta) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.HasPrev {
		i--
		if m.HasPrev {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if m.HasNext {
		i--
		if m.HasNext {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if m.Total != 0 {
		i = encodeVarintQueryLimitSwaps(dAtA, i, uint64(m.Total))
		i--
		dAtA[i] = 0x18
	}
	if m.Limit != 0 {
		i = encodeVarintQueryLimitSwaps(dAtA, i, uint64(m.Limit))
		i--
		dAtA[i] = 0x10
	}
	if m.Offset != 0 {
		i = encodeVarintQueryLimitSwaps(dAtA, i, uint64(m.Offset))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryLimitSwapsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLimitSwapsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLimitSwapsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQueryLimitSwaps(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.LimitSwaps) > 0 {
		for iNdEx := len(m.LimitSwaps) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.LimitSwaps[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQueryLimitSwaps(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQueryLimitSwaps(dAtA []byte, offset int, v uint64) int {
	offset -= sovQueryLimitSwaps(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryLimitSwapsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Height)
	if l > 0 {
		n += 1 + l + sovQueryLimitSwaps(uint64(l))
	}
	if m.Offset != 0 {
		n += 1 + sovQueryLimitSwaps(uint64(m.Offset))
	}
	if m.Limit != 0 {
		n += 1 + sovQueryLimitSwaps(uint64(m.Limit))
	}
	l = len(m.SourceAsset)
	if l > 0 {
		n += 1 + l + sovQueryLimitSwaps(uint64(l))
	}
	l = len(m.TargetAsset)
	if l > 0 {
		n += 1 + l + sovQueryLimitSwaps(uint64(l))
	}
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovQueryLimitSwaps(uint64(l))
	}
	l = len(m.SortBy)
	if l > 0 {
		n += 1 + l + sovQueryLimitSwaps(uint64(l))
	}
	l = len(m.SortOrder)
	if l > 0 {
		n += 1 + l + sovQueryLimitSwaps(uint64(l))
	}
	return n
}

func (m *LimitSwapWithDetails) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Swap != nil {
		l = m.Swap.Size()
		n += 1 + l + sovQueryLimitSwaps(uint64(l))
	}
	l = len(m.Ratio)
	if l > 0 {
		n += 1 + l + sovQueryLimitSwaps(uint64(l))
	}
	if m.BlocksSinceCreated != 0 {
		n += 1 + sovQueryLimitSwaps(uint64(m.BlocksSinceCreated))
	}
	if m.TimeToExpiryBlocks != 0 {
		n += 1 + sovQueryLimitSwaps(uint64(m.TimeToExpiryBlocks))
	}
	if m.CreatedTimestamp != 0 {
		n += 1 + sovQueryLimitSwaps(uint64(m.CreatedTimestamp))
	}
	return n
}

func (m *PaginationMeta) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Offset != 0 {
		n += 1 + sovQueryLimitSwaps(uint64(m.Offset))
	}
	if m.Limit != 0 {
		n += 1 + sovQueryLimitSwaps(uint64(m.Limit))
	}
	if m.Total != 0 {
		n += 1 + sovQueryLimitSwaps(uint64(m.Total))
	}
	if m.HasNext {
		n += 2
	}
	if m.HasPrev {
		n += 2
	}
	return n
}

func (m *QueryLimitSwapsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.LimitSwaps) > 0 {
		for _, e := range m.LimitSwaps {
			l = e.Size()
			n += 1 + l + sovQueryLimitSwaps(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQueryLimitSwaps(uint64(l))
	}
	return n
}

func sovQueryLimitSwaps(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQueryLimitSwaps(x uint64) (n int) {
	return sovQueryLimitSwaps(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryLimitSwapsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQueryLimitSwaps
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLimitSwapsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLimitSwapsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryLimitSwaps
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQueryLimitSwaps
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQueryLimitSwaps
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Height = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Offset", wireType)
			}
			m.Offset = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryLimitSwaps
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Offset |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Limit", wireType)
			}
			m.Limit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryLimitSwaps
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Limit |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceAsset", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryLimitSwaps
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQueryLimitSwaps
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQueryLimitSwaps
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceAsset = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetAsset", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryLimitSwaps
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQueryLimitSwaps
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQueryLimitSwaps
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TargetAsset = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryLimitSwaps
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQueryLimitSwaps
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQueryLimitSwaps
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SortBy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryLimitSwaps
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQueryLimitSwaps
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQueryLimitSwaps
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SortBy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SortOrder", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryLimitSwaps
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQueryLimitSwaps
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQueryLimitSwaps
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SortOrder = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQueryLimitSwaps(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQueryLimitSwaps
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LimitSwapWithDetails) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQueryLimitSwaps
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LimitSwapWithDetails: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LimitSwapWithDetails: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Swap", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryLimitSwaps
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQueryLimitSwaps
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQueryLimitSwaps
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Swap == nil {
				m.Swap = &MsgSwap{}
			}
			if err := m.Swap.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ratio", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryLimitSwaps
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQueryLimitSwaps
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQueryLimitSwaps
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ratio = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlocksSinceCreated", wireType)
			}
			m.BlocksSinceCreated = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryLimitSwaps
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlocksSinceCreated |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeToExpiryBlocks", wireType)
			}
			m.TimeToExpiryBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryLimitSwaps
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TimeToExpiryBlocks |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedTimestamp", wireType)
			}
			m.CreatedTimestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryLimitSwaps
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedTimestamp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQueryLimitSwaps(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQueryLimitSwaps
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PaginationMeta) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQueryLimitSwaps
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PaginationMeta: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PaginationMeta: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Offset", wireType)
			}
			m.Offset = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryLimitSwaps
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Offset |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Limit", wireType)
			}
			m.Limit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryLimitSwaps
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Limit |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Total", wireType)
			}
			m.Total = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryLimitSwaps
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Total |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HasNext", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryLimitSwaps
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.HasNext = bool(v != 0)
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HasPrev", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryLimitSwaps
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.HasPrev = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipQueryLimitSwaps(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQueryLimitSwaps
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLimitSwapsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQueryLimitSwaps
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLimitSwapsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLimitSwapsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LimitSwaps", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryLimitSwaps
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQueryLimitSwaps
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQueryLimitSwaps
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LimitSwaps = append(m.LimitSwaps, &LimitSwapWithDetails{})
			if err := m.LimitSwaps[len(m.LimitSwaps)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryLimitSwaps
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQueryLimitSwaps
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQueryLimitSwaps
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &PaginationMeta{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQueryLimitSwaps(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQueryLimitSwaps
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQueryLimitSwaps(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQueryLimitSwaps
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQueryLimitSwaps
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQueryLimitSwaps
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQueryLimitSwaps
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQueryLimitSwaps
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQueryLimitSwaps
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQueryLimitSwaps        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQueryLimitSwaps          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQueryLimitSwaps = fmt.Errorf("proto: unexpected end of group")
)
