// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: types/query_secured_asset.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QuerySecuredAssetRequest struct {
	Asset  string `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	Height string `protobuf:"bytes,2,opt,name=height,proto3" json:"height,omitempty"`
}

func (m *QuerySecuredAssetRequest) Reset()         { *m = QuerySecuredAssetRequest{} }
func (m *QuerySecuredAssetRequest) String() string { return proto.CompactTextString(m) }
func (*QuerySecuredAssetRequest) ProtoMessage()    {}
func (*QuerySecuredAssetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e4d07323f3a1b65, []int{0}
}
func (m *QuerySecuredAssetRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QuerySecuredAssetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QuerySecuredAssetRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QuerySecuredAssetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySecuredAssetRequest.Merge(m, src)
}
func (m *QuerySecuredAssetRequest) XXX_Size() int {
	return m.Size()
}
func (m *QuerySecuredAssetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySecuredAssetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySecuredAssetRequest proto.InternalMessageInfo

func (m *QuerySecuredAssetRequest) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

func (m *QuerySecuredAssetRequest) GetHeight() string {
	if m != nil {
		return m.Height
	}
	return ""
}

type QuerySecuredAssetResponse struct {
	// bridge account asset with \"-\" separator
	Asset string `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset"`
	// total share tokens issued for the pool
	Supply string `protobuf:"bytes,2,opt,name=supply,proto3" json:"supply"`
	// total depth of bridge asset
	Depth string `protobuf:"bytes,3,opt,name=depth,proto3" json:"depth"`
}

func (m *QuerySecuredAssetResponse) Reset()         { *m = QuerySecuredAssetResponse{} }
func (m *QuerySecuredAssetResponse) String() string { return proto.CompactTextString(m) }
func (*QuerySecuredAssetResponse) ProtoMessage()    {}
func (*QuerySecuredAssetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e4d07323f3a1b65, []int{1}
}
func (m *QuerySecuredAssetResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QuerySecuredAssetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QuerySecuredAssetResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QuerySecuredAssetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySecuredAssetResponse.Merge(m, src)
}
func (m *QuerySecuredAssetResponse) XXX_Size() int {
	return m.Size()
}
func (m *QuerySecuredAssetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySecuredAssetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySecuredAssetResponse proto.InternalMessageInfo

func (m *QuerySecuredAssetResponse) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

func (m *QuerySecuredAssetResponse) GetSupply() string {
	if m != nil {
		return m.Supply
	}
	return ""
}

func (m *QuerySecuredAssetResponse) GetDepth() string {
	if m != nil {
		return m.Depth
	}
	return ""
}

type QuerySecuredAssetsRequest struct {
	Height string `protobuf:"bytes,1,opt,name=height,proto3" json:"height,omitempty"`
}

func (m *QuerySecuredAssetsRequest) Reset()         { *m = QuerySecuredAssetsRequest{} }
func (m *QuerySecuredAssetsRequest) String() string { return proto.CompactTextString(m) }
func (*QuerySecuredAssetsRequest) ProtoMessage()    {}
func (*QuerySecuredAssetsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e4d07323f3a1b65, []int{2}
}
func (m *QuerySecuredAssetsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QuerySecuredAssetsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QuerySecuredAssetsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QuerySecuredAssetsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySecuredAssetsRequest.Merge(m, src)
}
func (m *QuerySecuredAssetsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QuerySecuredAssetsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySecuredAssetsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySecuredAssetsRequest proto.InternalMessageInfo

func (m *QuerySecuredAssetsRequest) GetHeight() string {
	if m != nil {
		return m.Height
	}
	return ""
}

type QuerySecuredAssetsResponse struct {
	Assets []*QuerySecuredAssetResponse `protobuf:"bytes,1,rep,name=assets,proto3" json:"assets,omitempty"`
}

func (m *QuerySecuredAssetsResponse) Reset()         { *m = QuerySecuredAssetsResponse{} }
func (m *QuerySecuredAssetsResponse) String() string { return proto.CompactTextString(m) }
func (*QuerySecuredAssetsResponse) ProtoMessage()    {}
func (*QuerySecuredAssetsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e4d07323f3a1b65, []int{3}
}
func (m *QuerySecuredAssetsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QuerySecuredAssetsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QuerySecuredAssetsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QuerySecuredAssetsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySecuredAssetsResponse.Merge(m, src)
}
func (m *QuerySecuredAssetsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QuerySecuredAssetsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySecuredAssetsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySecuredAssetsResponse proto.InternalMessageInfo

func (m *QuerySecuredAssetsResponse) GetAssets() []*QuerySecuredAssetResponse {
	if m != nil {
		return m.Assets
	}
	return nil
}

func init() {
	proto.RegisterType((*QuerySecuredAssetRequest)(nil), "types.QuerySecuredAssetRequest")
	proto.RegisterType((*QuerySecuredAssetResponse)(nil), "types.QuerySecuredAssetResponse")
	proto.RegisterType((*QuerySecuredAssetsRequest)(nil), "types.QuerySecuredAssetsRequest")
	proto.RegisterType((*QuerySecuredAssetsResponse)(nil), "types.QuerySecuredAssetsResponse")
}

func init() { proto.RegisterFile("types/query_secured_asset.proto", fileDescriptor_4e4d07323f3a1b65) }

var fileDescriptor_4e4d07323f3a1b65 = []byte{
	// 309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x6b, 0xaa, 0x46, 0xaa, 0xd9, 0xa2, 0x0a, 0x85, 0x0e, 0x4e, 0x95, 0xa9, 0x0b, 0xb1,
	0x44, 0x17, 0x56, 0x3a, 0xb1, 0x30, 0x10, 0x24, 0x06, 0x96, 0x2a, 0x4d, 0x4e, 0x71, 0xa5, 0x52,
	0xbb, 0x39, 0x47, 0x90, 0x91, 0x37, 0xe0, 0xb1, 0x18, 0x3b, 0x32, 0x55, 0x28, 0xd9, 0xfa, 0x14,
	0x28, 0x76, 0xaa, 0xaa, 0x52, 0x98, 0x2e, 0xf7, 0xe7, 0xfe, 0xcf, 0xff, 0xd9, 0xd4, 0xd7, 0xa5,
	0x02, 0xe4, 0xdb, 0x02, 0xf2, 0x72, 0x81, 0x90, 0x14, 0x39, 0xa4, 0x8b, 0x18, 0x11, 0x74, 0xa8,
	0x72, 0xa9, 0xa5, 0x3b, 0x30, 0x03, 0xe3, 0x51, 0x26, 0x33, 0x69, 0x14, 0xde, 0x7c, 0xd9, 0x9f,
	0xc1, 0x03, 0xf5, 0x9e, 0x1a, 0xe7, 0xb3, 0x35, 0xde, 0x37, 0xbe, 0x08, 0xb6, 0x05, 0xa0, 0x76,
	0x47, 0x74, 0x60, 0x38, 0x1e, 0x99, 0x90, 0xe9, 0x30, 0xb2, 0x8d, 0x7b, 0x45, 0x1d, 0x01, 0xab,
	0x4c, 0x68, 0xef, 0xc2, 0xc8, 0x6d, 0x17, 0x7c, 0x12, 0x7a, 0xdd, 0x81, 0x42, 0x25, 0x37, 0x08,
	0xae, 0x7f, 0xc6, 0x9a, 0x0f, 0x0f, 0x7b, 0xdf, 0x0a, 0x47, 0x6c, 0x40, 0x1d, 0x2c, 0x94, 0x5a,
	0x97, 0x16, 0x3b, 0xa7, 0x87, 0xbd, 0xdf, 0x2a, 0x51, 0x5b, 0x1b, 0x48, 0x0a, 0x4a, 0x0b, 0xaf,
	0x7f, 0x82, 0x18, 0x21, 0xb2, 0x25, 0x98, 0x75, 0x44, 0xc0, 0xe3, 0x3a, 0xa7, 0xe0, 0xe4, 0x2c,
	0xf8, 0x0b, 0x1d, 0x77, 0x99, 0xda, 0xe0, 0x77, 0xd4, 0x31, 0x01, 0xd1, 0x23, 0x93, 0xfe, 0xf4,
	0xf2, 0x76, 0x12, 0x9a, 0xeb, 0x0c, 0xff, 0x5d, 0x35, 0x6a, 0xe7, 0xe7, 0x8f, 0xdf, 0x15, 0x23,
	0xbb, 0x8a, 0x91, 0xdf, 0x8a, 0x91, 0xaf, 0x9a, 0xf5, 0x76, 0x35, 0xeb, 0xfd, 0xd4, 0xac, 0xf7,
	0x3a, 0xcb, 0x56, 0x5a, 0x14, 0xcb, 0x30, 0x91, 0x6f, 0x3c, 0x85, 0x24, 0xc6, 0xf7, 0x58, 0xdd,
	0xac, 0xe3, 0x25, 0x9a, 0x6e, 0x23, 0x53, 0xe0, 0x1f, 0x5c, 0x0b, 0x99, 0x27, 0x22, 0x5e, 0x6d,
	0xb8, 0x39, 0x70, 0xe9, 0x98, 0x07, 0x9b, 0xfd, 0x05, 0x00, 0x00, 0xff, 0xff, 0x2f, 0x9c, 0xa5,
	0x3d, 0xf0, 0x01, 0x00, 0x00,
}

func (m *QuerySecuredAssetRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QuerySecuredAssetRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QuerySecuredAssetRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Height) > 0 {
		i -= len(m.Height)
		copy(dAtA[i:], m.Height)
		i = encodeVarintQuerySecuredAsset(dAtA, i, uint64(len(m.Height)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Asset) > 0 {
		i -= len(m.Asset)
		copy(dAtA[i:], m.Asset)
		i = encodeVarintQuerySecuredAsset(dAtA, i, uint64(len(m.Asset)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QuerySecuredAssetResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QuerySecuredAssetResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QuerySecuredAssetResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Depth) > 0 {
		i -= len(m.Depth)
		copy(dAtA[i:], m.Depth)
		i = encodeVarintQuerySecuredAsset(dAtA, i, uint64(len(m.Depth)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Supply) > 0 {
		i -= len(m.Supply)
		copy(dAtA[i:], m.Supply)
		i = encodeVarintQuerySecuredAsset(dAtA, i, uint64(len(m.Supply)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Asset) > 0 {
		i -= len(m.Asset)
		copy(dAtA[i:], m.Asset)
		i = encodeVarintQuerySecuredAsset(dAtA, i, uint64(len(m.Asset)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QuerySecuredAssetsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QuerySecuredAssetsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QuerySecuredAssetsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Height) > 0 {
		i -= len(m.Height)
		copy(dAtA[i:], m.Height)
		i = encodeVarintQuerySecuredAsset(dAtA, i, uint64(len(m.Height)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QuerySecuredAssetsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QuerySecuredAssetsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QuerySecuredAssetsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Assets) > 0 {
		for iNdEx := len(m.Assets) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Assets[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuerySecuredAsset(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuerySecuredAsset(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuerySecuredAsset(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QuerySecuredAssetRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Asset)
	if l > 0 {
		n += 1 + l + sovQuerySecuredAsset(uint64(l))
	}
	l = len(m.Height)
	if l > 0 {
		n += 1 + l + sovQuerySecuredAsset(uint64(l))
	}
	return n
}

func (m *QuerySecuredAssetResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Asset)
	if l > 0 {
		n += 1 + l + sovQuerySecuredAsset(uint64(l))
	}
	l = len(m.Supply)
	if l > 0 {
		n += 1 + l + sovQuerySecuredAsset(uint64(l))
	}
	l = len(m.Depth)
	if l > 0 {
		n += 1 + l + sovQuerySecuredAsset(uint64(l))
	}
	return n
}

func (m *QuerySecuredAssetsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Height)
	if l > 0 {
		n += 1 + l + sovQuerySecuredAsset(uint64(l))
	}
	return n
}

func (m *QuerySecuredAssetsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Assets) > 0 {
		for _, e := range m.Assets {
			l = e.Size()
			n += 1 + l + sovQuerySecuredAsset(uint64(l))
		}
	}
	return n
}

func sovQuerySecuredAsset(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuerySecuredAsset(x uint64) (n int) {
	return sovQuerySecuredAsset(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QuerySecuredAssetRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuerySecuredAsset
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QuerySecuredAssetRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QuerySecuredAssetRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Asset", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuerySecuredAsset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuerySecuredAsset
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuerySecuredAsset
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Asset = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuerySecuredAsset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuerySecuredAsset
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuerySecuredAsset
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Height = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuerySecuredAsset(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuerySecuredAsset
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QuerySecuredAssetResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuerySecuredAsset
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QuerySecuredAssetResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QuerySecuredAssetResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Asset", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuerySecuredAsset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuerySecuredAsset
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuerySecuredAsset
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Asset = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Supply", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuerySecuredAsset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuerySecuredAsset
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuerySecuredAsset
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Supply = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Depth", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuerySecuredAsset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuerySecuredAsset
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuerySecuredAsset
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Depth = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuerySecuredAsset(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuerySecuredAsset
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QuerySecuredAssetsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuerySecuredAsset
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QuerySecuredAssetsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QuerySecuredAssetsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuerySecuredAsset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuerySecuredAsset
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuerySecuredAsset
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Height = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuerySecuredAsset(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuerySecuredAsset
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QuerySecuredAssetsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuerySecuredAsset
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QuerySecuredAssetsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QuerySecuredAssetsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Assets", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuerySecuredAsset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuerySecuredAsset
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuerySecuredAsset
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Assets = append(m.Assets, &QuerySecuredAssetResponse{})
			if err := m.Assets[len(m.Assets)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuerySecuredAsset(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuerySecuredAsset
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuerySecuredAsset(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuerySecuredAsset
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuerySecuredAsset
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuerySecuredAsset
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuerySecuredAsset
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuerySecuredAsset
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuerySecuredAsset
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuerySecuredAsset        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuerySecuredAsset          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuerySecuredAsset = fmt.Errorf("proto: unexpected end of group")
)
