// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: types/type_errata_tx_voter.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_decaswap_labs_decanode_common "github.com/decaswap-labs/decanode/common"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ErrataTxVoter struct {
	TxID        github_com_decaswap_labs_decanode_common.TxID  `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3,casttype=github.com/decaswap-labs/decanode/common.TxID" json:"tx_id,omitempty"`
	Chain       github_com_decaswap_labs_decanode_common.Chain `protobuf:"bytes,2,opt,name=chain,proto3,casttype=github.com/decaswap-labs/decanode/common.Chain" json:"chain,omitempty"`
	BlockHeight int64                                          `protobuf:"varint,3,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	Signers     []string                                       `protobuf:"bytes,4,rep,name=signers,proto3" json:"signers,omitempty"`
}

func (m *ErrataTxVoter) Reset()      { *m = ErrataTxVoter{} }
func (*ErrataTxVoter) ProtoMessage() {}
func (*ErrataTxVoter) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbd88b378975a5a7, []int{0}
}
func (m *ErrataTxVoter) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ErrataTxVoter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ErrataTxVoter.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ErrataTxVoter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrataTxVoter.Merge(m, src)
}
func (m *ErrataTxVoter) XXX_Size() int {
	return m.Size()
}
func (m *ErrataTxVoter) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrataTxVoter.DiscardUnknown(m)
}

var xxx_messageInfo_ErrataTxVoter proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ErrataTxVoter)(nil), "types.ErrataTxVoter")
}

func init() { proto.RegisterFile("types/type_errata_tx_voter.proto", fileDescriptor_bbd88b378975a5a7) }

var fileDescriptor_bbd88b378975a5a7 = []byte{
	// 295 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0x31, 0x4f, 0x84, 0x30,
	0x00, 0x85, 0x5b, 0x01, 0xcd, 0x55, 0x5d, 0x88, 0x03, 0x71, 0x28, 0xe8, 0xc4, 0x72, 0x90, 0x78,
	0x93, 0xeb, 0xa9, 0xc9, 0xdd, 0xe2, 0x40, 0x2e, 0x26, 0xba, 0x90, 0x02, 0x0d, 0x10, 0x0f, 0x4a,
	0xda, 0xaa, 0x75, 0xf3, 0x27, 0xf8, 0xb3, 0x6e, 0xbc, 0xf1, 0x26, 0xe2, 0x41, 0xe2, 0x8f, 0xb8,
	0xc9, 0xd0, 0x8b, 0xb3, 0x2e, 0x4d, 0xdf, 0x6b, 0xbf, 0x97, 0x97, 0x87, 0x3c, 0xf9, 0xde, 0x50,
	0x11, 0x0e, 0x67, 0x4c, 0x39, 0x27, 0x92, 0xc4, 0x52, 0xc5, 0xaf, 0x4c, 0x52, 0x1e, 0x34, 0x9c,
	0x49, 0x66, 0x5b, 0xfa, 0xc7, 0xf9, 0x59, 0xce, 0x72, 0xa6, 0x9d, 0x70, 0xb8, 0xed, 0x1f, 0x2f,
	0xbf, 0x21, 0x3a, 0xbd, 0xd3, 0xd8, 0x42, 0x3d, 0x0c, 0x90, 0x7d, 0x8f, 0x2c, 0xa9, 0xe2, 0x32,
	0x73, 0xa0, 0x07, 0xfd, 0xd1, 0xf4, 0xba, 0x6b, 0x5d, 0x73, 0xa1, 0xe6, 0xb7, 0xbb, 0xd6, 0x1d,
	0xe7, 0xa5, 0x2c, 0x5e, 0x92, 0x20, 0x65, 0x55, 0x98, 0xd1, 0x94, 0x88, 0x37, 0xd2, 0x8c, 0x97,
	0x24, 0x11, 0x5a, 0xd5, 0x2c, 0xa3, 0x61, 0xca, 0xaa, 0x8a, 0xd5, 0xc1, 0x00, 0x44, 0xa6, 0x54,
	0xf3, 0xcc, 0x9e, 0x21, 0x2b, 0x2d, 0x48, 0x59, 0x3b, 0x07, 0x3a, 0xef, 0x6a, 0xd7, 0xba, 0xc1,
	0xbf, 0x73, 0x6e, 0x06, 0x32, 0xda, 0x07, 0xd8, 0x17, 0xe8, 0x24, 0x59, 0xb2, 0xf4, 0x39, 0x2e,
	0x68, 0x99, 0x17, 0xd2, 0x31, 0x3c, 0xe8, 0x1b, 0xd1, 0xb1, 0xf6, 0x66, 0xda, 0xb2, 0x1d, 0x74,
	0x24, 0xca, 0xbc, 0xa6, 0x5c, 0x38, 0xa6, 0x67, 0xf8, 0xa3, 0xe8, 0x57, 0x4e, 0x1f, 0x57, 0x5b,
	0x0c, 0x36, 0x5b, 0x0c, 0x3e, 0x3a, 0x0c, 0x56, 0x1d, 0x86, 0xeb, 0x0e, 0xc3, 0xaf, 0x0e, 0xc3,
	0xcf, 0x1e, 0x83, 0x75, 0x8f, 0xc1, 0xa6, 0xc7, 0xe0, 0x69, 0xf2, 0x77, 0x33, 0x15, 0xca, 0x82,
	0x71, 0xdd, 0x48, 0xaf, 0x2e, 0x92, 0x43, 0x3d, 0xe5, 0xe4, 0x27, 0x00, 0x00, 0xff, 0xff, 0x2a,
	0x9b, 0x73, 0xb0, 0x8b, 0x01, 0x00, 0x00,
}

func (m *ErrataTxVoter) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ErrataTxVoter) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ErrataTxVoter) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signers) > 0 {
		for iNdEx := len(m.Signers) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Signers[iNdEx])
			copy(dAtA[i:], m.Signers[iNdEx])
			i = encodeVarintTypeErrataTxVoter(dAtA, i, uint64(len(m.Signers[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if m.BlockHeight != 0 {
		i = encodeVarintTypeErrataTxVoter(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Chain) > 0 {
		i -= len(m.Chain)
		copy(dAtA[i:], m.Chain)
		i = encodeVarintTypeErrataTxVoter(dAtA, i, uint64(len(m.Chain)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.TxID) > 0 {
		i -= len(m.TxID)
		copy(dAtA[i:], m.TxID)
		i = encodeVarintTypeErrataTxVoter(dAtA, i, uint64(len(m.TxID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypeErrataTxVoter(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypeErrataTxVoter(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ErrataTxVoter) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TxID)
	if l > 0 {
		n += 1 + l + sovTypeErrataTxVoter(uint64(l))
	}
	l = len(m.Chain)
	if l > 0 {
		n += 1 + l + sovTypeErrataTxVoter(uint64(l))
	}
	if m.BlockHeight != 0 {
		n += 1 + sovTypeErrataTxVoter(uint64(m.BlockHeight))
	}
	if len(m.Signers) > 0 {
		for _, s := range m.Signers {
			l = len(s)
			n += 1 + l + sovTypeErrataTxVoter(uint64(l))
		}
	}
	return n
}

func sovTypeErrataTxVoter(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypeErrataTxVoter(x uint64) (n int) {
	return sovTypeErrataTxVoter(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ErrataTxVoter) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypeErrataTxVoter
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ErrataTxVoter: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ErrataTxVoter: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeErrataTxVoter
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypeErrataTxVoter
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypeErrataTxVoter
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxID = github_com_decaswap_labs_decanode_common.TxID(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Chain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeErrataTxVoter
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypeErrataTxVoter
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypeErrataTxVoter
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Chain = github_com_decaswap_labs_decanode_common.Chain(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeErrataTxVoter
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signers", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeErrataTxVoter
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypeErrataTxVoter
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypeErrataTxVoter
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signers = append(m.Signers, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypeErrataTxVoter(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypeErrataTxVoter
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypeErrataTxVoter(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypeErrataTxVoter
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypeErrataTxVoter
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypeErrataTxVoter
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypeErrataTxVoter
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypeErrataTxVoter
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypeErrataTxVoter
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypeErrataTxVoter        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypeErrataTxVoter          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypeErrataTxVoter = fmt.Errorf("proto: unexpected end of group")
)
