#!/bin/bash
# analyze_profiles.sh - Analyze pprof profiles and generate reports
#
# This script analyzes CPU, memory, and other profiles generated by benchmarks
# and produces human-readable reports highlighting bottlenecks.
#
# Usage:
#   ./analyze_profiles.sh <profile_directory>
#
# Example:
#   ./analyze_profiles.sh results/20250105_143022

set -e

if [ $# -lt 1 ]; then
  echo "Usage: $0 <profile_directory>"
  echo ""
  echo "Example: $0 results/20250105_143022"
  exit 1
fi

PROFILE_DIR="$1"
REPORT_DIR="$PROFILE_DIR/reports"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

log_info() {
  echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
  echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
  echo -e "${RED}[ERROR]${NC} $1"
}

# Check if profile directory exists
if [ ! -d "$PROFILE_DIR" ]; then
  log_error "Profile directory not found: $PROFILE_DIR"
  exit 1
fi

mkdir -p "$REPORT_DIR"

log_info "Analyzing profiles in: $PROFILE_DIR"
log_info "Reports will be saved to: $REPORT_DIR"
echo ""

# Function to analyze a profile
analyze_profile() {
  local profile_file=$1
  local profile_type=$2

  if [ ! -f "$profile_file" ]; then
    log_warn "$profile_type profile not found: $profile_file"
    return
  fi

  log_info "Analyzing $profile_type profile..."

  # Generate text report with top functions
  go tool pprof -text -flat "$profile_file" >"$REPORT_DIR/${profile_type}_flat.txt" 2>&1 || true
  go tool pprof -text -cum "$profile_file" >"$REPORT_DIR/${profile_type}_cumulative.txt" 2>&1 || true

  # Generate call graph
  go tool pprof -dot "$profile_file" >"$REPORT_DIR/${profile_type}_callgraph.dot" 2>&1 || true

  # Generate flame graph (if graphviz is installed)
  if command -v dot >/dev/null 2>&1; then
    dot -Tpng "$REPORT_DIR/${profile_type}_callgraph.dot" \
      -o "$REPORT_DIR/${profile_type}_callgraph.png" 2>&1 || true
  fi

  # Extract top 20 functions
  echo "${GREEN}Top 20 Functions ($profile_type):${NC}" >"$REPORT_DIR/${profile_type}_top20.txt"
  go tool pprof -text -flat "$profile_file" 2>&1 | head -30 >>"$REPORT_DIR/${profile_type}_top20.txt" || true

  # Show specific package stats (thorchain)
  echo "" >>"$REPORT_DIR/${profile_type}_top20.txt"
  echo "${GREEN}THORChain Package Functions:${NC}" >>"$REPORT_DIR/${profile_type}_top20.txt"
  go tool pprof -text -flat "$profile_file" 2>&1 | grep "thorchain" | head -30 >>"$REPORT_DIR/${profile_type}_top20.txt" || true
}

# Analyze each profile type
analyze_profile "$PROFILE_DIR/cpu.prof" "cpu"
analyze_profile "$PROFILE_DIR/mem.prof" "memory"
analyze_profile "$PROFILE_DIR/block.prof" "block"
analyze_profile "$PROFILE_DIR/mutex.prof" "mutex"

# Display CPU profile top functions
if [ -f "$REPORT_DIR/cpu_top20.txt" ]; then
  echo ""
  log_info "CPU Profile - Top Functions:"
  echo "======================================================================"
  head -30 "$REPORT_DIR/cpu_top20.txt"
  echo ""
fi

# Display memory profile top functions
if [ -f "$REPORT_DIR/memory_top20.txt" ]; then
  echo ""
  log_info "Memory Profile - Top Allocations:"
  echo "======================================================================"
  head -30 "$REPORT_DIR/memory_top20.txt"
  echo ""
fi

# Check for common performance issues
log_info "Checking for common performance issues..."
echo ""

if [ -f "$PROFILE_DIR/cpu.prof" ]; then
  # Check for excessive reflection
  if go tool pprof -text "$PROFILE_DIR/cpu.prof" 2>&1 | grep -i "reflect\." >/dev/null; then
    log_warn "Reflection detected in hot path - may impact performance"
    go tool pprof -text "$PROFILE_DIR/cpu.prof" 2>&1 | grep -i "reflect\." | head -5
  fi

  # Check for JSON marshaling/unmarshaling
  if go tool pprof -text "$PROFILE_DIR/cpu.prof" 2>&1 | grep -E "json\.(Marshal|Unmarshal)" >/dev/null; then
    log_warn "JSON marshaling detected in hot path"
    go tool pprof -text "$PROFILE_DIR/cpu.prof" 2>&1 | grep -E "json\.(Marshal|Unmarshal)" | head -5
  fi

  # Check for database operations
  if go tool pprof -text "$PROFILE_DIR/cpu.prof" 2>&1 | grep -E "GetAdvSwapQueue|SetAdvSwapQueue" >/dev/null; then
    log_warn "Advanced swap queue operations detected - analyzing..."
    go tool pprof -text "$PROFILE_DIR/cpu.prof" 2>&1 | grep -E "AdvSwap" | head -10
  fi
fi

# Generate comparison report if benchmark results exist
if [ -f "$PROFILE_DIR/benchmark.txt" ]; then
  log_info "Generating benchmark comparison report..."

  python3 - <<'EOF'
import re
import sys

try:
    with open('$PROFILE_DIR/benchmark.txt', 'r') as f:
        content = f.read()

    # Extract benchmark results
    results = {}
    pattern = r'Benchmark(\w+)/(\w+)-\d+\s+\d+\s+(\d+)\s+ns/op'

    for match in re.finditer(pattern, content):
        bench_name = match.group(1)
        variant = match.group(2)
        ns_per_op = int(match.group(3))

        if bench_name not in results:
            results[bench_name] = {}
        results[bench_name][variant] = ns_per_op

    # Print comparison
    print("\n\033[0;32m[INFO]\033[0m Benchmark Comparison Report:")
    print("=" * 80)

    for bench_name, variants in results.items():
        print(f"\n{bench_name}:")

        if 'Queue_Disabled' in variants and 'Queue_Enabled' in variants:
            disabled = variants['Queue_Disabled']
            enabled = variants['Queue_Enabled']

            slowdown = enabled / disabled if disabled > 0 else 0

            print(f"  Queue Disabled: {disabled:>12,} ns/op  ({disabled/1e6:.2f} ms)")
            print(f"  Queue Enabled:  {enabled:>12,} ns/op  ({enabled/1e6:.2f} ms)")
            print(f"  Slowdown:       {slowdown:>12.2f}x")

            if slowdown > 10:
                print(f"  \033[0;31m[!] WARNING: Significant performance degradation detected!\033[0m")
            elif slowdown > 2:
                print(f"  \033[1;33m[!] CAUTION: Moderate performance impact\033[0m")

except Exception as e:
    print(f"Error generating comparison: {e}", file=sys.stderr)
EOF
fi

echo ""
log_info "Analysis complete!"
echo ""
log_info "Generated reports:"
find "$REPORT_DIR" -name "*.txt" -type f -print 2>/dev/null | while read -r file; do echo "  - $file"; done || true
if command -v dot >/dev/null 2>&1; then
  find "$REPORT_DIR" -name "*.png" -type f -print 2>/dev/null | while read -r file; do echo "  - $file"; done || true
fi

echo ""
log_info "To view interactive CPU profile:"
echo "  go tool pprof -http=:8080 $PROFILE_DIR/cpu.prof"
echo ""
log_info "To view interactive memory profile:"
echo "  go tool pprof -http=:8080 $PROFILE_DIR/mem.prof"
echo ""
log_info "To view execution trace:"
if [ -f "$PROFILE_DIR/trace.out" ]; then
  echo "  go tool trace $PROFILE_DIR/trace.out"
else
  echo "  (trace.out not found)"
fi
