// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: thorchain/denom/v1/types/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryDenomAdminRequest struct {
	Denom string `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty" yaml:"denom"`
}

func (m *QueryDenomAdminRequest) Reset()         { *m = QueryDenomAdminRequest{} }
func (m *QueryDenomAdminRequest) String() string { return proto.CompactTextString(m) }
func (*QueryDenomAdminRequest) ProtoMessage()    {}
func (*QueryDenomAdminRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a35ea2e3dcf140eb, []int{0}
}
func (m *QueryDenomAdminRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDenomAdminRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDenomAdminRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDenomAdminRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDenomAdminRequest.Merge(m, src)
}
func (m *QueryDenomAdminRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryDenomAdminRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDenomAdminRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDenomAdminRequest proto.InternalMessageInfo

func (m *QueryDenomAdminRequest) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

type QueryDenomAdminResponse struct {
	Admin string `protobuf:"bytes,1,opt,name=admin,proto3" json:"admin,omitempty" yaml:"denom"`
}

func (m *QueryDenomAdminResponse) Reset()         { *m = QueryDenomAdminResponse{} }
func (m *QueryDenomAdminResponse) String() string { return proto.CompactTextString(m) }
func (*QueryDenomAdminResponse) ProtoMessage()    {}
func (*QueryDenomAdminResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a35ea2e3dcf140eb, []int{1}
}
func (m *QueryDenomAdminResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDenomAdminResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDenomAdminResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDenomAdminResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDenomAdminResponse.Merge(m, src)
}
func (m *QueryDenomAdminResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryDenomAdminResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDenomAdminResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDenomAdminResponse proto.InternalMessageInfo

func (m *QueryDenomAdminResponse) GetAdmin() string {
	if m != nil {
		return m.Admin
	}
	return ""
}

func init() {
	proto.RegisterType((*QueryDenomAdminRequest)(nil), "thorchain.denom.v1.QueryDenomAdminRequest")
	proto.RegisterType((*QueryDenomAdminResponse)(nil), "thorchain.denom.v1.QueryDenomAdminResponse")
}

func init() {
	proto.RegisterFile("thorchain/denom/v1/types/query.proto", fileDescriptor_a35ea2e3dcf140eb)
}

var fileDescriptor_a35ea2e3dcf140eb = []byte{
	// 332 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x31, 0x4b, 0xc3, 0x50,
	0x14, 0x85, 0xfb, 0x84, 0x0a, 0x3e, 0x1c, 0x24, 0xa8, 0x95, 0xa2, 0x51, 0x82, 0x88, 0x54, 0xcc,
	0x25, 0xba, 0x39, 0xd9, 0xe2, 0xe2, 0x68, 0x47, 0xb7, 0x9b, 0xe4, 0x91, 0x06, 0x9a, 0x77, 0xd3,
	0xbe, 0xd7, 0x6a, 0x11, 0x17, 0x71, 0x16, 0xc1, 0x3f, 0xe5, 0x58, 0x70, 0x71, 0x12, 0x69, 0xfd,
	0x05, 0xfe, 0x02, 0xc9, 0x4d, 0xd1, 0xa1, 0x0a, 0x4e, 0xc9, 0xbb, 0xe7, 0xe3, 0xdc, 0xc3, 0x3d,
	0x72, 0xd7, 0x76, 0xa8, 0x1f, 0x75, 0x30, 0xd5, 0x10, 0x2b, 0x4d, 0x19, 0x0c, 0x03, 0xb0, 0xa3,
	0x5c, 0x19, 0xe8, 0x0d, 0x54, 0x7f, 0xe4, 0xe7, 0x7d, 0xb2, 0xe4, 0x38, 0xdf, 0x94, 0xcf, 0x94,
	0x3f, 0x0c, 0xea, 0xab, 0x09, 0x25, 0xc4, 0x32, 0x14, 0x7f, 0x25, 0x59, 0xdf, 0x4c, 0x88, 0x92,
	0xae, 0x02, 0xcc, 0x53, 0x40, 0xad, 0xc9, 0xa2, 0x4d, 0x49, 0x9b, 0x99, 0xda, 0x88, 0xc8, 0x64,
	0x64, 0x20, 0x44, 0xa3, 0xca, 0x05, 0x30, 0x0c, 0x42, 0x65, 0x31, 0x80, 0x1c, 0x93, 0x54, 0x33,
	0x5c, 0xb2, 0xde, 0xa9, 0x5c, 0xbf, 0x28, 0x88, 0xb3, 0x62, 0x61, 0x33, 0xce, 0x52, 0xdd, 0x56,
	0xbd, 0x81, 0x32, 0xd6, 0xd9, 0x93, 0x55, 0x4e, 0xb1, 0x21, 0x76, 0xc4, 0xfe, 0x52, 0x6b, 0xe5,
	0xf3, 0x6d, 0x7b, 0x79, 0x84, 0x59, 0xf7, 0xc4, 0xe3, 0xb1, 0xd7, 0x2e, 0x65, 0xaf, 0x29, 0x6b,
	0x73, 0x0e, 0x26, 0x27, 0x6d, 0x54, 0x61, 0x81, 0xc5, 0xe0, 0x6f, 0x0b, 0x96, 0x8f, 0x1e, 0x84,
	0xac, 0xb2, 0x87, 0x73, 0x2f, 0xa4, 0xfc, 0x31, 0x72, 0x1a, 0xfe, 0xfc, 0x49, 0xfc, 0xdf, 0xf3,
	0xd6, 0x0f, 0xfe, 0xc5, 0x96, 0xc9, 0xbc, 0xad, 0xbb, 0x97, 0x8f, 0xa7, 0x85, 0x9a, 0xb3, 0x56,
	0xf6, 0x61, 0xe0, 0x86, 0xbf, 0xb7, 0xc0, 0x81, 0x5a, 0xe7, 0xcf, 0x13, 0x57, 0x8c, 0x27, 0xae,
	0x78, 0x9f, 0xb8, 0xe2, 0x71, 0xea, 0x56, 0xc6, 0x53, 0xb7, 0xf2, 0x3a, 0x75, 0x2b, 0x97, 0x90,
	0xa4, 0xb6, 0x33, 0x08, 0xfd, 0x88, 0x32, 0x88, 0x55, 0x84, 0xe6, 0x0a, 0xf3, 0xc3, 0x2e, 0x86,
	0x86, 0x5f, 0x9a, 0x62, 0x05, 0xd7, 0xb3, 0x8e, 0xb9, 0xe0, 0x70, 0x91, 0xef, 0x7c, 0xfc, 0x15,
	0x00, 0x00, 0xff, 0xff, 0x1a, 0x79, 0x0f, 0xde, 0x03, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	DenomAdmin(ctx context.Context, in *QueryDenomAdminRequest, opts ...grpc.CallOption) (*QueryDenomAdminResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) DenomAdmin(ctx context.Context, in *QueryDenomAdminRequest, opts ...grpc.CallOption) (*QueryDenomAdminResponse, error) {
	out := new(QueryDenomAdminResponse)
	err := c.cc.Invoke(ctx, "/thorchain.denom.v1.Query/DenomAdmin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	DenomAdmin(context.Context, *QueryDenomAdminRequest) (*QueryDenomAdminResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) DenomAdmin(ctx context.Context, req *QueryDenomAdminRequest) (*QueryDenomAdminResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DenomAdmin not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_DenomAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDenomAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DenomAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/thorchain.denom.v1.Query/DenomAdmin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DenomAdmin(ctx, req.(*QueryDenomAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "thorchain.denom.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DenomAdmin",
			Handler:    _Query_DenomAdmin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "thorchain/denom/v1/types/query.proto",
}

func (m *QueryDenomAdminRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDenomAdminRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDenomAdminRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryDenomAdminResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDenomAdminResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDenomAdminResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Admin) > 0 {
		i -= len(m.Admin)
		copy(dAtA[i:], m.Admin)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Admin)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryDenomAdminRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryDenomAdminResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Admin)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryDenomAdminRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDenomAdminRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDenomAdminRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDenomAdminResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDenomAdminResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDenomAdminResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Admin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Admin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
